#!/usr/bin/env bash
#
# teste-dialog-1 Teste de daloag para Yes e No
#
# 0.0.1 2022-04-16 Jefferson Santana
# - Início do programa
# - Página que pergunta o que quer fazer
# - Criado if que filtra o que vem da pregunta
# - Colocado um clear para limpar a tela antes de mostrar a hora

dialog --yesno 'Quer ver as horas?' 0 0

if [ $? = 0 ]; then

  clear && echo "Agora são: $( date )"

else

  echo 'Ok, não vou mostrar as horas.'

fi
